### ISSUE TITLE
Add cdn info

### ISSUE THREAD

**Issue by PeterDaveHello** [tnhu/jsface#24]
HI @tnhu,

I'm Peter from cdnjs.com,

I wonder if you would like to add cdn info in the readme ?

This is the page we provide cdn for jsface - https://cdnjs.com/libraries/jsface

Thanks!

**Comment by tnhu** [comment]
Hi Peter,

Sorry being late. Does cdnjs update version automatically? I.e. if I increase jsface to 2.4.0, the version appears on cdnjs immediately?

Thanks,
Tan

**Comment by PeterDaveHello** [comment]
Yes, we update from npm package within 24 hours.

**Comment by tnhu** [comment]
Thanks Peter. Added.

**Comment by PeterDaveHello** [comment]
:+1:
