### ISSUE TITLE
$statics do not work

### ISSUE THREAD

**Issue by caetanator** [tnhu/jsface#29]
$statics do not work in 2.4.0 and 2.4.1 on Google Chrome 42.0.2311.135.

All static methods and properties are undefined on derived objects

Code:

"use strict"; // Activates ECMA JavaScript 5 strict mode
		
		var Person = Class({
			  $statics: {
			    MIN_AGE:   1,
			    MAX_AGE: 150,
			 
			    isValidAge: function(age) {
			      return age >= this.MIN_AGE && age <= this.MAX_AGE;
			    }
			  },
			 
			  constructor: function(name, age) {
			    this.name = name;
			    this.age  = age;
			  }
			});
			 
			var person = new Person("Rika", 20);
			 
			Person.MIN_AGE === person.MIN_AGE;               // person.MIN_AGE == undefined
			Person.MAX_AGE === person.MAX_AGE;               // person.MAX_AGE== undefined
			Person.isValidAge(0);                            // false 
			person.isValidAge(person.age);                   // person.isValidAge== undefined.

**Comment by tnhu** [comment]
Jose,

Since 2.4.0, static properties are available on class only and not instances (@seee https://github.com/tnhu/jsface/issues/25).
