### ISSUE TITLE
Invalid CDN link

### ISSUE THREAD

**Issue by marcus-nl** [tnhu/jsface#31]
The link https://cdnjs.cloudflare.com/ajax/libs/jsface/2.4.0/jsface.js does not work. It seems only versions 2.3.0 and 2.2.0 are on cdnjs.

This link does work for me: http://cdn.jsdelivr.net/jsface/2.4.6/jsface.min.js

**Comment by tnhu** [comment]
Thanks Marcus, should be fixed in 2.4.7.
