### ISSUE TITLE
Super's constructor not getting called if sub class not defining constructor (yes, again).

### ISSUE THREAD

**Issue by sunrize531** [tnhu/jsface#32]
Just reopening this issue: https://github.com/tnhu/jsface/issues/13

Actually it's a first OOP model I ever seen, which behaves this way. In most cases you **expect** parent's constructor to be called. If you don't need parent's class constructor to be called from child class, you could define constructor in child class without a $super call, right?

Nope. Not in this library. You **have** to create an empty constructors, containing only super's call here.

**Comment by webprogramozo** [comment]
+1

**Comment by vursen** [comment]
+1

**Comment by tnhu** [comment]
This should be fixed in 2.4.10. Thanks everyone for reporting!

P.S: I apology for being super late.
