### ISSUE TITLE
Uncaught ReferenceError: extend is not defined

### ISSUE THREAD

**Issue by PompolutZ** [tnhu/jsface#36]
I get this error when I try this example:

var Student = Class(Person, {
  constructor: function(id, name, age) {
});

extend(Student, [ Options, Events ]);

I've tried both referencing jsface and include it in the script

**Comment by tnhu** [comment]
`extend` is not exposed to global scope like Class. Could you try?

```js
var extend = jsface.extend;

var Student = Class(Person, {
constructor: function(id, name, age) {
});

extend(Student, [ Options, Events ]);
```

**Comment by PompolutZ** [comment]
Yes, sorry I've been sloppy not to see it on my own. I've noticed that after I've posted this issue. On the other hand, why not to expose extend by default, especially if it is mentioned in tutorials?

But thanks for respond.

**Comment by tnhu** [comment]
Hi PompolutZ, JSFace introduces two namespaces `jsface` and `Class` to global context to minimize global namespace pollution. The other reason is to eliminate conflict with other libraries or frameworks (think if you have two libs in which both introduce `extend` to global context).
