### ISSUE TITLE
getters & inheritance don't work (gets evaluated while inheriting)

### ISSUE THREAD

**Issue by RonenNess** [tnhu/jsface#37]
Consider the following code:

```

// define a class with a getter
var test1 = Class({

    constructor: function(socket)
    {
        this._should_exist = {yep: true};
    },

    // this getter will mess things up...
    should_exist: {
        get: function() {
            return this._should_exist.yep;
        }
    },
});

// then inherit from it.
// this part will evaluate the 'should_exist' getter and will cause exception, since _should_exist is not yet defined.
var test2 = Class(test1, {

});

```

The code above will invoke exception: TypeError: Cannot read property 'yep' of undefined. The reason for that, I assume, is because probably somewhere inside jsface tries to copy the prototype attribute should_exist, but instead of copying the definition it tries to evaluate it to return the value.

I didn't look too deep into it though.

**Comment by tnhu** [comment]
Thank you for reporting. This is a very interesting bug. I'm working on it.
